/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.news.letter.model.impl;

import com.liferay.training.news.letter.model.NewsLetter_Articles;
import com.liferay.training.news.letter.service.NewsLetter_ArticlesLocalServiceUtil;

/**
 * The extended model base implementation for the NewsLetter_Articles service. Represents a row in the &quot;NEWSLETTER_NewsLetter_Articles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This class exists only as a container for the default extended model level methods generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsLetter_ArticlesImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsLetter_ArticlesImpl
 * @see NewsLetter_Articles
 * @generated
 */
public abstract class NewsLetter_ArticlesBaseImpl
	extends NewsLetter_ArticlesModelImpl implements NewsLetter_Articles {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news letter_ articles model instance should use the <code>NewsLetter_Articles</code> interface instead.
	 */
	@Override
	public void persist() {
		if (this.isNew()) {
			NewsLetter_ArticlesLocalServiceUtil.addNewsLetter_Articles(this);
		}
		else {
			NewsLetter_ArticlesLocalServiceUtil.updateNewsLetter_Articles(this);
		}
	}

}