/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.news.letter.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.ProxyUtil;
import com.liferay.training.news.letter.model.NewsLetter;
import com.liferay.training.news.letter.model.NewsLetterModel;
import com.liferay.training.news.letter.model.NewsLetterSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the NewsLetter service. Represents a row in the &quot;NEWSLETTER_NewsLetter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>NewsLetterModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link NewsLetterImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsLetterImpl
 * @generated
 */
@JSON(strict = true)
public class NewsLetterModelImpl
	extends BaseModelImpl<NewsLetter> implements NewsLetterModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a news letter model instance should use the <code>NewsLetter</code> interface instead.
	 */
	public static final String TABLE_NAME = "NEWSLETTER_NewsLetter";

	public static final Object[][] TABLE_COLUMNS = {
		{"newsletterId", Types.BIGINT}, {"groupId", Types.BIGINT},
		{"companyId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"userName", Types.VARCHAR}, {"createDate", Types.TIMESTAMP},
		{"issueDate", Types.TIMESTAMP}, {"issueNumber", Types.INTEGER},
		{"title", Types.VARCHAR}, {"description", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("newsletterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("issueDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("issueNumber", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("description", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table NEWSLETTER_NewsLetter (newsletterId LONG not null primary key,groupId LONG,companyId LONG,userId LONG,userName VARCHAR(75) null,createDate DATE null,issueDate DATE null,issueNumber INTEGER,title VARCHAR(300) null,description VARCHAR(300) null)";

	public static final String TABLE_SQL_DROP =
		"drop table NEWSLETTER_NewsLetter";

	public static final String ORDER_BY_JPQL =
		" ORDER BY newsLetter.newsletterId ASC";

	public static final String ORDER_BY_SQL =
		" ORDER BY NEWSLETTER_NewsLetter.newsletterId ASC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static NewsLetter toModel(NewsLetterSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		NewsLetter model = new NewsLetterImpl();

		model.setNewsletterId(soapModel.getNewsletterId());
		model.setGroupId(soapModel.getGroupId());
		model.setCompanyId(soapModel.getCompanyId());
		model.setUserId(soapModel.getUserId());
		model.setUserName(soapModel.getUserName());
		model.setCreateDate(soapModel.getCreateDate());
		model.setIssueDate(soapModel.getIssueDate());
		model.setIssueNumber(soapModel.getIssueNumber());
		model.setTitle(soapModel.getTitle());
		model.setDescription(soapModel.getDescription());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<NewsLetter> toModels(NewsLetterSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<NewsLetter> models = new ArrayList<NewsLetter>(soapModels.length);

		for (NewsLetterSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public NewsLetterModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _newsletterId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setNewsletterId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _newsletterId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return NewsLetter.class;
	}

	@Override
	public String getModelClassName() {
		return NewsLetter.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<NewsLetter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<NewsLetter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsLetter, Object> attributeGetterFunction =
				entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((NewsLetter)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<NewsLetter, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<NewsLetter, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept(
					(NewsLetter)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<NewsLetter, Object>>
		getAttributeGetterFunctions() {

		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<NewsLetter, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, NewsLetter>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			NewsLetter.class.getClassLoader(), NewsLetter.class,
			ModelWrapper.class);

		try {
			Constructor<NewsLetter> constructor =
				(Constructor<NewsLetter>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<NewsLetter, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<NewsLetter, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<NewsLetter, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<NewsLetter, Object>>();
		Map<String, BiConsumer<NewsLetter, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<NewsLetter, ?>>();

		attributeGetterFunctions.put(
			"newsletterId", NewsLetter::getNewsletterId);
		attributeSetterBiConsumers.put(
			"newsletterId",
			(BiConsumer<NewsLetter, Long>)NewsLetter::setNewsletterId);
		attributeGetterFunctions.put("groupId", NewsLetter::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<NewsLetter, Long>)NewsLetter::setGroupId);
		attributeGetterFunctions.put("companyId", NewsLetter::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId",
			(BiConsumer<NewsLetter, Long>)NewsLetter::setCompanyId);
		attributeGetterFunctions.put("userId", NewsLetter::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<NewsLetter, Long>)NewsLetter::setUserId);
		attributeGetterFunctions.put("userName", NewsLetter::getUserName);
		attributeSetterBiConsumers.put(
			"userName",
			(BiConsumer<NewsLetter, String>)NewsLetter::setUserName);
		attributeGetterFunctions.put("createDate", NewsLetter::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate",
			(BiConsumer<NewsLetter, Date>)NewsLetter::setCreateDate);
		attributeGetterFunctions.put("issueDate", NewsLetter::getIssueDate);
		attributeSetterBiConsumers.put(
			"issueDate",
			(BiConsumer<NewsLetter, Date>)NewsLetter::setIssueDate);
		attributeGetterFunctions.put("issueNumber", NewsLetter::getIssueNumber);
		attributeSetterBiConsumers.put(
			"issueNumber",
			(BiConsumer<NewsLetter, Integer>)NewsLetter::setIssueNumber);
		attributeGetterFunctions.put("title", NewsLetter::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<NewsLetter, String>)NewsLetter::setTitle);
		attributeGetterFunctions.put("description", NewsLetter::getDescription);
		attributeSetterBiConsumers.put(
			"description",
			(BiConsumer<NewsLetter, String>)NewsLetter::setDescription);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public long getNewsletterId() {
		return _newsletterId;
	}

	@Override
	public void setNewsletterId(long newsletterId) {
		_newsletterId = newsletterId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_groupId = groupId;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_companyId = companyId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	@JSON
	@Override
	public String getUserName() {
		if (_userName == null) {
			return "";
		}
		else {
			return _userName;
		}
	}

	@Override
	public void setUserName(String userName) {
		_userName = userName;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getIssueDate() {
		return _issueDate;
	}

	@Override
	public void setIssueDate(Date issueDate) {
		_issueDate = issueDate;
	}

	@JSON
	@Override
	public Integer getIssueNumber() {
		return _issueNumber;
	}

	@Override
	public void setIssueNumber(Integer issueNumber) {
		_issueNumber = issueNumber;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_title = title;
	}

	@JSON
	@Override
	public String getDescription() {
		if (_description == null) {
			return "";
		}
		else {
			return _description;
		}
	}

	@Override
	public void setDescription(String description) {
		_description = description;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), NewsLetter.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public NewsLetter toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, NewsLetter>
				escapedModelProxyProviderFunction =
					EscapedModelProxyProviderFunctionHolder.
						_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		NewsLetterImpl newsLetterImpl = new NewsLetterImpl();

		newsLetterImpl.setNewsletterId(getNewsletterId());
		newsLetterImpl.setGroupId(getGroupId());
		newsLetterImpl.setCompanyId(getCompanyId());
		newsLetterImpl.setUserId(getUserId());
		newsLetterImpl.setUserName(getUserName());
		newsLetterImpl.setCreateDate(getCreateDate());
		newsLetterImpl.setIssueDate(getIssueDate());
		newsLetterImpl.setIssueNumber(getIssueNumber());
		newsLetterImpl.setTitle(getTitle());
		newsLetterImpl.setDescription(getDescription());

		newsLetterImpl.resetOriginalValues();

		return newsLetterImpl;
	}

	@Override
	public int compareTo(NewsLetter newsLetter) {
		long primaryKey = newsLetter.getPrimaryKey();

		if (getPrimaryKey() < primaryKey) {
			return -1;
		}
		else if (getPrimaryKey() > primaryKey) {
			return 1;
		}
		else {
			return 0;
		}
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof NewsLetter)) {
			return false;
		}

		NewsLetter newsLetter = (NewsLetter)obj;

		long primaryKey = newsLetter.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
	}

	@Override
	public CacheModel<NewsLetter> toCacheModel() {
		NewsLetterCacheModel newsLetterCacheModel = new NewsLetterCacheModel();

		newsLetterCacheModel.newsletterId = getNewsletterId();

		newsLetterCacheModel.groupId = getGroupId();

		newsLetterCacheModel.companyId = getCompanyId();

		newsLetterCacheModel.userId = getUserId();

		newsLetterCacheModel.userName = getUserName();

		String userName = newsLetterCacheModel.userName;

		if ((userName != null) && (userName.length() == 0)) {
			newsLetterCacheModel.userName = null;
		}

		Date createDate = getCreateDate();

		if (createDate != null) {
			newsLetterCacheModel.createDate = createDate.getTime();
		}
		else {
			newsLetterCacheModel.createDate = Long.MIN_VALUE;
		}

		Date issueDate = getIssueDate();

		if (issueDate != null) {
			newsLetterCacheModel.issueDate = issueDate.getTime();
		}
		else {
			newsLetterCacheModel.issueDate = Long.MIN_VALUE;
		}

		newsLetterCacheModel.issueNumber = getIssueNumber();

		newsLetterCacheModel.title = getTitle();

		String title = newsLetterCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			newsLetterCacheModel.title = null;
		}

		newsLetterCacheModel.description = getDescription();

		String description = newsLetterCacheModel.description;

		if ((description != null) && (description.length() == 0)) {
			newsLetterCacheModel.description = null;
		}

		return newsLetterCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<NewsLetter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<NewsLetter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsLetter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((NewsLetter)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<NewsLetter, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<NewsLetter, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<NewsLetter, Object> attributeGetterFunction =
				entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((NewsLetter)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, NewsLetter>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private long _newsletterId;
	private long _groupId;
	private long _companyId;
	private long _userId;
	private String _userName;
	private Date _createDate;
	private Date _issueDate;
	private Integer _issueNumber;
	private String _title;
	private String _description;
	private NewsLetter _escapedModel;

}