/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ResourcedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NewsletterArticle service. Represents a row in the &quot;NEWSLETTER_NewsletterArticle&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.newsletter.model.impl.NewsletterArticleModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.newsletter.model.impl.NewsletterArticleImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsletterArticle
 * @generated
 */
@ProviderType
public interface NewsletterArticleModel
	extends BaseModel<NewsletterArticle>, ResourcedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a newsletter article model instance should use the {@link NewsletterArticle} interface instead.
	 */

	/**
	 * Returns the primary key of this newsletter article.
	 *
	 * @return the primary key of this newsletter article
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this newsletter article.
	 *
	 * @param primaryKey the primary key of this newsletter article
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the newsletter article ID of this newsletter article.
	 *
	 * @return the newsletter article ID of this newsletter article
	 */
	public long getNewsletterArticleId();

	/**
	 * Sets the newsletter article ID of this newsletter article.
	 *
	 * @param newsletterArticleId the newsletter article ID of this newsletter article
	 */
	public void setNewsletterArticleId(long newsletterArticleId);

	/**
	 * Returns the group ID of this newsletter article.
	 *
	 * @return the group ID of this newsletter article
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this newsletter article.
	 *
	 * @param groupId the group ID of this newsletter article
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this newsletter article.
	 *
	 * @return the company ID of this newsletter article
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this newsletter article.
	 *
	 * @param companyId the company ID of this newsletter article
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this newsletter article.
	 *
	 * @return the user ID of this newsletter article
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this newsletter article.
	 *
	 * @param userId the user ID of this newsletter article
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this newsletter article.
	 *
	 * @return the user uuid of this newsletter article
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this newsletter article.
	 *
	 * @param userUuid the user uuid of this newsletter article
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the author of this newsletter article.
	 *
	 * @return the author of this newsletter article
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this newsletter article.
	 *
	 * @param author the author of this newsletter article
	 */
	public void setAuthor(String author);

	/**
	 * Returns the create date of this newsletter article.
	 *
	 * @return the create date of this newsletter article
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this newsletter article.
	 *
	 * @param createDate the create date of this newsletter article
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this newsletter article.
	 *
	 * @return the modified date of this newsletter article
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this newsletter article.
	 *
	 * @param modifiedDate the modified date of this newsletter article
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the issue number of this newsletter article.
	 *
	 * @return the issue number of this newsletter article
	 */
	public Integer getIssueNumber();

	/**
	 * Sets the issue number of this newsletter article.
	 *
	 * @param issueNumber the issue number of this newsletter article
	 */
	public void setIssueNumber(Integer issueNumber);

	/**
	 * Returns the title of this newsletter article.
	 *
	 * @return the title of this newsletter article
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this newsletter article.
	 *
	 * @param title the title of this newsletter article
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this newsletter article.
	 *
	 * @return the content of this newsletter article
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this newsletter article.
	 *
	 * @param content the content of this newsletter article
	 */
	public void setContent(String content);

	/**
	 * Returns the resource prim key of this newsletter article.
	 *
	 * @return the resource prim key of this newsletter article
	 */
	@Override
	public long getResourcePrimKey();

	/**
	 * Sets the resource prim key of this newsletter article.
	 *
	 * @param resourcePrimKey the resource prim key of this newsletter article
	 */
	@Override
	public void setResourcePrimKey(long resourcePrimKey);

	@Override
	public boolean isResourceMain();

	/**
	 * Returns the status of this newsletter article.
	 *
	 * @return the status of this newsletter article
	 */
	public int getStatus();

	/**
	 * Sets the status of this newsletter article.
	 *
	 * @param status the status of this newsletter article
	 */
	public void setStatus(int status);

}