/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.amf.registration.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the UserCustom service. Represents a row in the &quot;AMF_REGISTRATION_UserCustom&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.amf.registration.model.impl.UserCustomModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.amf.registration.model.impl.UserCustomImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see UserCustom
 * @generated
 */
@ProviderType
public interface UserCustomModel
	extends BaseModel<UserCustom>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a user custom model instance should use the {@link UserCustom} interface instead.
	 */

	/**
	 * Returns the primary key of this user custom.
	 *
	 * @return the primary key of this user custom
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this user custom.
	 *
	 * @param primaryKey the primary key of this user custom
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the user custom ID of this user custom.
	 *
	 * @return the user custom ID of this user custom
	 */
	public long getUserCustomId();

	/**
	 * Sets the user custom ID of this user custom.
	 *
	 * @param userCustomId the user custom ID of this user custom
	 */
	public void setUserCustomId(long userCustomId);

	/**
	 * Returns the group ID of this user custom.
	 *
	 * @return the group ID of this user custom
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this user custom.
	 *
	 * @param groupId the group ID of this user custom
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this user custom.
	 *
	 * @return the company ID of this user custom
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this user custom.
	 *
	 * @param companyId the company ID of this user custom
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this user custom.
	 *
	 * @return the user ID of this user custom
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this user custom.
	 *
	 * @param userId the user ID of this user custom
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this user custom.
	 *
	 * @return the user uuid of this user custom
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this user custom.
	 *
	 * @param userUuid the user uuid of this user custom
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this user custom.
	 *
	 * @return the user name of this user custom
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this user custom.
	 *
	 * @param userName the user name of this user custom
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this user custom.
	 *
	 * @return the create date of this user custom
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this user custom.
	 *
	 * @param createDate the create date of this user custom
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this user custom.
	 *
	 * @return the modified date of this user custom
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this user custom.
	 *
	 * @param modifiedDate the modified date of this user custom
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the male of this user custom.
	 *
	 * @return the male of this user custom
	 */
	public boolean getMale();

	/**
	 * Returns <code>true</code> if this user custom is male.
	 *
	 * @return <code>true</code> if this user custom is male; <code>false</code> otherwise
	 */
	public boolean isMale();

	/**
	 * Sets whether this user custom is male.
	 *
	 * @param male the male of this user custom
	 */
	public void setMale(boolean male);

	/**
	 * Returns the home phone of this user custom.
	 *
	 * @return the home phone of this user custom
	 */
	@AutoEscape
	public String getHomePhone();

	/**
	 * Sets the home phone of this user custom.
	 *
	 * @param homePhone the home phone of this user custom
	 */
	public void setHomePhone(String homePhone);

	/**
	 * Returns the mobile phone of this user custom.
	 *
	 * @return the mobile phone of this user custom
	 */
	@AutoEscape
	public String getMobilePhone();

	/**
	 * Sets the mobile phone of this user custom.
	 *
	 * @param mobilePhone the mobile phone of this user custom
	 */
	public void setMobilePhone(String mobilePhone);

}