/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the Newsletters service. Represents a row in the &quot;NEWSLETTER_Newsletters&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.newsletter.model.impl.NewslettersModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.newsletter.model.impl.NewslettersImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see Newsletters
 * @generated
 */
@ProviderType
public interface NewslettersModel
	extends BaseModel<Newsletters>, GroupedModel, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a newsletters model instance should use the {@link Newsletters} interface instead.
	 */

	/**
	 * Returns the primary key of this newsletters.
	 *
	 * @return the primary key of this newsletters
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this newsletters.
	 *
	 * @param primaryKey the primary key of this newsletters
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the newsletters ID of this newsletters.
	 *
	 * @return the newsletters ID of this newsletters
	 */
	public long getNewslettersId();

	/**
	 * Sets the newsletters ID of this newsletters.
	 *
	 * @param newslettersId the newsletters ID of this newsletters
	 */
	public void setNewslettersId(long newslettersId);

	/**
	 * Returns the group ID of this newsletters.
	 *
	 * @return the group ID of this newsletters
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this newsletters.
	 *
	 * @param groupId the group ID of this newsletters
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this newsletters.
	 *
	 * @return the company ID of this newsletters
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this newsletters.
	 *
	 * @param companyId the company ID of this newsletters
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this newsletters.
	 *
	 * @return the user ID of this newsletters
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this newsletters.
	 *
	 * @param userId the user ID of this newsletters
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this newsletters.
	 *
	 * @return the user uuid of this newsletters
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this newsletters.
	 *
	 * @param userUuid the user uuid of this newsletters
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this newsletters.
	 *
	 * @return the user name of this newsletters
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this newsletters.
	 *
	 * @param userName the user name of this newsletters
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this newsletters.
	 *
	 * @return the create date of this newsletters
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this newsletters.
	 *
	 * @param createDate the create date of this newsletters
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this newsletters.
	 *
	 * @return the modified date of this newsletters
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this newsletters.
	 *
	 * @param modifiedDate the modified date of this newsletters
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the issue number of this newsletters.
	 *
	 * @return the issue number of this newsletters
	 */
	public Integer getIssueNumber();

	/**
	 * Sets the issue number of this newsletters.
	 *
	 * @param issueNumber the issue number of this newsletters
	 */
	public void setIssueNumber(Integer issueNumber);

	/**
	 * Returns the title of this newsletters.
	 *
	 * @return the title of this newsletters
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this newsletters.
	 *
	 * @param title the title of this newsletters
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this newsletters.
	 *
	 * @return the description of this newsletters
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this newsletters.
	 *
	 * @param description the description of this newsletters
	 */
	public void setDescription(String description);

	/**
	 * Returns the issue date of this newsletters.
	 *
	 * @return the issue date of this newsletters
	 */
	public Date getIssueDate();

	/**
	 * Sets the issue date of this newsletters.
	 *
	 * @param issueDate the issue date of this newsletters
	 */
	public void setIssueDate(Date issueDate);

}