/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.newsletter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NewslettersArticles service. Represents a row in the &quot;NEWSLETTER_NewslettersArticles&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.newsletter.model.impl.NewslettersArticlesModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.newsletter.model.impl.NewslettersArticlesImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewslettersArticles
 * @generated
 */
@ProviderType
public interface NewslettersArticlesModel
	extends BaseModel<NewslettersArticles>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a newsletters articles model instance should use the {@link NewslettersArticles} interface instead.
	 */

	/**
	 * Returns the primary key of this newsletters articles.
	 *
	 * @return the primary key of this newsletters articles
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this newsletters articles.
	 *
	 * @param primaryKey the primary key of this newsletters articles
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the newsletters articles ID of this newsletters articles.
	 *
	 * @return the newsletters articles ID of this newsletters articles
	 */
	public long getNewslettersArticlesId();

	/**
	 * Sets the newsletters articles ID of this newsletters articles.
	 *
	 * @param newslettersArticlesId the newsletters articles ID of this newsletters articles
	 */
	public void setNewslettersArticlesId(long newslettersArticlesId);

	/**
	 * Returns the group ID of this newsletters articles.
	 *
	 * @return the group ID of this newsletters articles
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this newsletters articles.
	 *
	 * @param groupId the group ID of this newsletters articles
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this newsletters articles.
	 *
	 * @return the company ID of this newsletters articles
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this newsletters articles.
	 *
	 * @param companyId the company ID of this newsletters articles
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this newsletters articles.
	 *
	 * @return the user ID of this newsletters articles
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this newsletters articles.
	 *
	 * @param userId the user ID of this newsletters articles
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this newsletters articles.
	 *
	 * @return the user uuid of this newsletters articles
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this newsletters articles.
	 *
	 * @param userUuid the user uuid of this newsletters articles
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the author of this newsletters articles.
	 *
	 * @return the author of this newsletters articles
	 */
	@AutoEscape
	public String getAuthor();

	/**
	 * Sets the author of this newsletters articles.
	 *
	 * @param author the author of this newsletters articles
	 */
	public void setAuthor(String author);

	/**
	 * Returns the create date of this newsletters articles.
	 *
	 * @return the create date of this newsletters articles
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this newsletters articles.
	 *
	 * @param createDate the create date of this newsletters articles
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this newsletters articles.
	 *
	 * @return the modified date of this newsletters articles
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this newsletters articles.
	 *
	 * @param modifiedDate the modified date of this newsletters articles
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the issue number of this newsletters articles.
	 *
	 * @return the issue number of this newsletters articles
	 */
	public Integer getIssueNumber();

	/**
	 * Sets the issue number of this newsletters articles.
	 *
	 * @param issueNumber the issue number of this newsletters articles
	 */
	public void setIssueNumber(Integer issueNumber);

	/**
	 * Returns the title of this newsletters articles.
	 *
	 * @return the title of this newsletters articles
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this newsletters articles.
	 *
	 * @param title the title of this newsletters articles
	 */
	public void setTitle(String title);

	/**
	 * Returns the content of this newsletters articles.
	 *
	 * @return the content of this newsletters articles
	 */
	@AutoEscape
	public String getContent();

	/**
	 * Sets the content of this newsletters articles.
	 *
	 * @param content the content of this newsletters articles
	 */
	public void setContent(String content);

}