/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.newsletter.service.base;

import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.training.newsletter.model.NewslettersArticles;
import com.liferay.training.newsletter.service.NewslettersArticlesLocalService;
import com.liferay.training.newsletter.service.persistence.NewslettersArticlesPersistence;
import com.liferay.training.newsletter.service.persistence.NewslettersPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the newsletters articles local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.liferay.training.newsletter.service.impl.NewslettersArticlesLocalServiceImpl}.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see com.liferay.training.newsletter.service.impl.NewslettersArticlesLocalServiceImpl
 * @generated
 */
public abstract class NewslettersArticlesLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService,
			   NewslettersArticlesLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>NewslettersArticlesLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.liferay.training.newsletter.service.NewslettersArticlesLocalServiceUtil</code>.
	 */

	/**
	 * Adds the newsletters articles to the database. Also notifies the appropriate model listeners.
	 *
	 * @param newslettersArticles the newsletters articles
	 * @return the newsletters articles that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NewslettersArticles addNewslettersArticles(
		NewslettersArticles newslettersArticles) {

		newslettersArticles.setNew(true);

		return newslettersArticlesPersistence.update(newslettersArticles);
	}

	/**
	 * Creates a new newsletters articles with the primary key. Does not add the newsletters articles to the database.
	 *
	 * @param newslettersArticlesId the primary key for the new newsletters articles
	 * @return the new newsletters articles
	 */
	@Override
	@Transactional(enabled = false)
	public NewslettersArticles createNewslettersArticles(
		long newslettersArticlesId) {

		return newslettersArticlesPersistence.create(newslettersArticlesId);
	}

	/**
	 * Deletes the newsletters articles with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param newslettersArticlesId the primary key of the newsletters articles
	 * @return the newsletters articles that was removed
	 * @throws PortalException if a newsletters articles with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NewslettersArticles deleteNewslettersArticles(
			long newslettersArticlesId)
		throws PortalException {

		return newslettersArticlesPersistence.remove(newslettersArticlesId);
	}

	/**
	 * Deletes the newsletters articles from the database. Also notifies the appropriate model listeners.
	 *
	 * @param newslettersArticles the newsletters articles
	 * @return the newsletters articles that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public NewslettersArticles deleteNewslettersArticles(
		NewslettersArticles newslettersArticles) {

		return newslettersArticlesPersistence.remove(newslettersArticles);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			NewslettersArticles.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return newslettersArticlesPersistence.findWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.training.newsletter.model.impl.NewslettersArticlesModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return newslettersArticlesPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.training.newsletter.model.impl.NewslettersArticlesModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return newslettersArticlesPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return newslettersArticlesPersistence.countWithDynamicQuery(
			dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return newslettersArticlesPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public NewslettersArticles fetchNewslettersArticles(
		long newslettersArticlesId) {

		return newslettersArticlesPersistence.fetchByPrimaryKey(
			newslettersArticlesId);
	}

	/**
	 * Returns the newsletters articles with the primary key.
	 *
	 * @param newslettersArticlesId the primary key of the newsletters articles
	 * @return the newsletters articles
	 * @throws PortalException if a newsletters articles with the primary key could not be found
	 */
	@Override
	public NewslettersArticles getNewslettersArticles(
			long newslettersArticlesId)
		throws PortalException {

		return newslettersArticlesPersistence.findByPrimaryKey(
			newslettersArticlesId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(
			newslettersArticlesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NewslettersArticles.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"newslettersArticlesId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			newslettersArticlesLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(
			NewslettersArticles.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"newslettersArticlesId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(
			newslettersArticlesLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(NewslettersArticles.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName(
			"newslettersArticlesId");
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return newslettersArticlesLocalService.deleteNewslettersArticles(
			(NewslettersArticles)persistedModel);
	}

	public BasePersistence<NewslettersArticles> getBasePersistence() {
		return newslettersArticlesPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return newslettersArticlesPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns a range of all the newsletters articleses.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.liferay.training.newsletter.model.impl.NewslettersArticlesModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of newsletters articleses
	 * @param end the upper bound of the range of newsletters articleses (not inclusive)
	 * @return the range of newsletters articleses
	 */
	@Override
	public List<NewslettersArticles> getNewslettersArticleses(
		int start, int end) {

		return newslettersArticlesPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of newsletters articleses.
	 *
	 * @return the number of newsletters articleses
	 */
	@Override
	public int getNewslettersArticlesesCount() {
		return newslettersArticlesPersistence.countAll();
	}

	/**
	 * Updates the newsletters articles in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param newslettersArticles the newsletters articles
	 * @return the newsletters articles that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public NewslettersArticles updateNewslettersArticles(
		NewslettersArticles newslettersArticles) {

		return newslettersArticlesPersistence.update(newslettersArticles);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			NewslettersArticlesLocalService.class,
			IdentifiableOSGiService.class, PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		newslettersArticlesLocalService =
			(NewslettersArticlesLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return NewslettersArticlesLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return NewslettersArticles.class;
	}

	protected String getModelClassName() {
		return NewslettersArticles.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource =
				newslettersArticlesPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected NewslettersPersistence newslettersPersistence;

	protected NewslettersArticlesLocalService newslettersArticlesLocalService;

	@Reference
	protected NewslettersArticlesPersistence newslettersArticlesPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.GroupLocalService
		groupLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}