/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.liferay.training.news.letter.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.ShardedModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the NewsLetter service. Represents a row in the &quot;NEWSLETTER_NewsLetter&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.liferay.training.news.letter.model.impl.NewsLetterModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.liferay.training.news.letter.model.impl.NewsLetterImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see NewsLetter
 * @generated
 */
@ProviderType
public interface NewsLetterModel extends BaseModel<NewsLetter>, ShardedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a news letter model instance should use the {@link NewsLetter} interface instead.
	 */

	/**
	 * Returns the primary key of this news letter.
	 *
	 * @return the primary key of this news letter
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this news letter.
	 *
	 * @param primaryKey the primary key of this news letter
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the newsletter ID of this news letter.
	 *
	 * @return the newsletter ID of this news letter
	 */
	public long getNewsletterId();

	/**
	 * Sets the newsletter ID of this news letter.
	 *
	 * @param newsletterId the newsletter ID of this news letter
	 */
	public void setNewsletterId(long newsletterId);

	/**
	 * Returns the group ID of this news letter.
	 *
	 * @return the group ID of this news letter
	 */
	public long getGroupId();

	/**
	 * Sets the group ID of this news letter.
	 *
	 * @param groupId the group ID of this news letter
	 */
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this news letter.
	 *
	 * @return the company ID of this news letter
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this news letter.
	 *
	 * @param companyId the company ID of this news letter
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this news letter.
	 *
	 * @return the user ID of this news letter
	 */
	public long getUserId();

	/**
	 * Sets the user ID of this news letter.
	 *
	 * @param userId the user ID of this news letter
	 */
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this news letter.
	 *
	 * @return the user uuid of this news letter
	 */
	public String getUserUuid();

	/**
	 * Sets the user uuid of this news letter.
	 *
	 * @param userUuid the user uuid of this news letter
	 */
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this news letter.
	 *
	 * @return the user name of this news letter
	 */
	@AutoEscape
	public String getUserName();

	/**
	 * Sets the user name of this news letter.
	 *
	 * @param userName the user name of this news letter
	 */
	public void setUserName(String userName);

	/**
	 * Returns the create date of this news letter.
	 *
	 * @return the create date of this news letter
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this news letter.
	 *
	 * @param createDate the create date of this news letter
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the issue date of this news letter.
	 *
	 * @return the issue date of this news letter
	 */
	public Date getIssueDate();

	/**
	 * Sets the issue date of this news letter.
	 *
	 * @param issueDate the issue date of this news letter
	 */
	public void setIssueDate(Date issueDate);

	/**
	 * Returns the issue number of this news letter.
	 *
	 * @return the issue number of this news letter
	 */
	public Integer getIssueNumber();

	/**
	 * Sets the issue number of this news letter.
	 *
	 * @param issueNumber the issue number of this news letter
	 */
	public void setIssueNumber(Integer issueNumber);

	/**
	 * Returns the title of this news letter.
	 *
	 * @return the title of this news letter
	 */
	@AutoEscape
	public String getTitle();

	/**
	 * Sets the title of this news letter.
	 *
	 * @param title the title of this news letter
	 */
	public void setTitle(String title);

	/**
	 * Returns the description of this news letter.
	 *
	 * @return the description of this news letter
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this news letter.
	 *
	 * @param description the description of this news letter
	 */
	public void setDescription(String description);

}